//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by generate-icons.js.
//
//


/**
 * A list of all available icons in the icon set.
 */
export type IconDefinition = 'chevron-down' | 'chevron-up' | 'done' | 'to-do';

export const availableIcons: IconDefinition[] = ['chevron-down', 'chevron-up', 'done', 'to-do'];

export const IconSvg = {
  'chevron-down': <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M8 10.609 14.333 4l.667.696L8 12 1 4.696 1.667 4 8 10.609Z" fill='currentColor'/></svg>,
  'chevron-up': <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M8 5.391 14.333 12l.667-.696L8 4l-7 7.304.667.696L8 5.391Z" fill='currentColor'/></svg>,
  'done': <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M11.081 7.483a.4.4 0 1 0-.565-.565l-3.317 3.316-.917-.916a.4.4 0 1 0-.565.565l1.2 1.2a.398.398 0 0 0 .564 0l3.6-3.6ZM8.4 1.6a.4.4 0 0 0-.282.118.395.395 0 0 0 0 .564A.4.4 0 1 0 8.4 1.6Zm-2.241.968c.31-.163.64-.168.64-.168a.4.4 0 0 0 .4-.4 1.201 1.201 0 0 1 2.4 0c0 .221.177.4.399.4.003 0 .333.005.643.168a.971.971 0 0 1 .511.632H5.648a.97.97 0 0 1 .51-.632ZM5.199 4h6.4a.4.4 0 0 0 .4-.4l-.001-.022c-.006-.793-.367-1.41-1.02-1.736a2.35 2.35 0 0 0-.612-.203 2.003 2.003 0 0 0-1.967-1.64C7.42 0 6.602.709 6.432 1.64a2.366 2.366 0 0 0-.61.203C5.161 2.171 4.8 2.796 4.8 3.6c0 .221.179.4.4.4ZM14 2.4h-.8a.4.4 0 0 0 0 .8h.8a.4.4 0 0 1 .4.4v11.2a.4.4 0 0 1-.4.4H2.8a.4.4 0 0 1-.4-.4V3.6c0-.221.18-.4.4-.4h.8a.4.4 0 1 0 0-.8h-.8c-.661 0-1.2.538-1.2 1.2v11.2c0 .662.539 1.2 1.2 1.2H14a1.2 1.2 0 0 0 1.2-1.2V3.6c0-.662-.537-1.2-1.2-1.2Z" fill='currentColor'/></svg>,
  'to-do': <svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" clipRule="evenodd" d="M11.624 4.067h-6.4a.4.4 0 0 1-.424-.4 1.856 1.856 0 0 1 1.048-1.8c.193-.095.397-.162.608-.2a2 2 0 0 1 3.944 0c.21.051.412.132.6.24a1.848 1.848 0 0 1 1.024 1.76.4.4 0 0 1-.4.4Zm-4.8-1.6a1.6 1.6 0 0 0-.64.168.968.968 0 0 0-.512.632H11.2a.968.968 0 0 0-.56-.632 1.6 1.6 0 0 0-.64-.168.4.4 0 0 1-.4-.4 1.2 1.2 0 0 0-2.4 0 .4.4 0 0 1-.376.4Zm1.32-.68a.4.4 0 0 1 .28-.12.4.4 0 0 1 0 .8.392.392 0 0 1-.304-.12.408.408 0 0 1-.12-.28.392.392 0 0 1 .144-.28ZM1.6 16.067h13.6V2.69h-2.4v.8h1.648v11.776H2.4V3.492h1.448v-.8H1.6v13.376Zm8-3.2H4.8v-.8h4.8v.8Zm-4.8-2.4h4.8v-.8H4.8v.8Zm6.4-2.4H4.8v-.8h6.4v.8Z" fill='currentColor'/></svg>,
};
